include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for Network Setting
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+luci-compat +luci-lib-jsonc

PKG_NAME:=luci-app-fwx-network
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

