#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for fwx feature library upgrade
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+luci-compat +luci-app-fwx-resources
PKG_NAME:=luci-app-fwx-feature
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk
# call BuildPackage - OpenWrt buildroot signature

